//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIagua.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aguaEntities : DbContext
    {
        public aguaEntities()
            : base("name=aguaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deposito> depositos { get; set; }
        public virtual DbSet<presa> presas { get; set; }
        public virtual DbSet<registroDeposito> registroDepositoes { get; set; }
        public virtual DbSet<registroPresa> registroPresas { get; set; }
        public virtual DbSet<registroTanque> registroTanques { get; set; }
        public virtual DbSet<tanque> tanques { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
    }
}
