//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIagua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registroDeposito
    {
        public int id { get; set; }
        public Nullable<int> id_deposito { get; set; }
        public Nullable<decimal> registro { get; set; }
    }
}
